/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sinh_tiling_data.h
 * \brief sinh TilingData structure for ascend950 (arch35)
 */
#ifndef _SINH_TILING_DATA_H_
#define _SINH_TILING_DATA_H_

struct SinhTilingData {
    int64_t totalNum = 0;      // Total number of elements
    int64_t blockFactor = 0;   // Number of elements per AI Core
    int64_t ubFactor = 0;      // Number of elements per UB loop iteration
};

#endif
