/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sinh.h
 * \brief sinh kernel class for ascend950 (arch35)
 *
 * Computes sinh(x) = (exp(x) - exp(-x)) / 2 for each element.
 */
#ifndef SINH_H
#define SINH_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "sinh_tiling_data.h"
#include "sinh_tiling_key.h"

namespace NsSinh {

using namespace AscendC;

constexpr int32_t BUFFER_NUM = 2;

template <typename T>
class Sinh {
public:
    __aicore__ inline Sinh() {};

    __aicore__ inline void Init(GM_ADDR x, GM_ADDR y, const SinhTilingData* tilingData);
    __aicore__ inline void Process();

private:
    __aicore__ inline void CopyIn(int64_t progress, int64_t currentNum);
    __aicore__ inline void CopyOut(int64_t progress, int64_t currentNum);
    __aicore__ inline void Compute(int64_t currentNum);

private:
    TPipe pipe;
    TQue<QuePosition::VECIN, BUFFER_NUM> inputQueue;
    TQue<QuePosition::VECOUT, BUFFER_NUM> outputQueue;
    TBuf<QuePosition::VECCALC> tmpBuf1;
    TBuf<QuePosition::VECCALC> tmpBuf2;

    GlobalTensor<T> inputGM;
    GlobalTensor<T> outputGM;

    int64_t blockLength_ = 0;
    int64_t ubLength_ = 0;
};

// ============================================================================
// Init - Initialize GM pointers and allocate UB buffers
// ============================================================================
template <typename T>
__aicore__ inline void Sinh<T>::Init(GM_ADDR x, GM_ADDR y, const SinhTilingData* tilingData)
{
    int64_t remainderLength = tilingData->totalNum - tilingData->blockFactor * AscendC::GetBlockIdx();
    blockLength_ = (remainderLength > tilingData->blockFactor) ? tilingData->blockFactor : remainderLength;
    if (blockLength_ < 0) {
        blockLength_ = 0;
    }
    ubLength_ = tilingData->ubFactor;

    if (blockLength_ <= 0 || ubLength_ <= 0) {
        return;
    }

    inputGM.SetGlobalBuffer((__gm__ T*)x + tilingData->blockFactor * AscendC::GetBlockIdx(), blockLength_);
    outputGM.SetGlobalBuffer((__gm__ T*)y + tilingData->blockFactor * AscendC::GetBlockIdx(), blockLength_);

    pipe.InitBuffer(inputQueue, BUFFER_NUM, ubLength_ * sizeof(T));
    pipe.InitBuffer(outputQueue, BUFFER_NUM, ubLength_ * sizeof(T));
    pipe.InitBuffer(tmpBuf1, ubLength_ * sizeof(float));
    pipe.InitBuffer(tmpBuf2, ubLength_ * sizeof(float));
}

// ============================================================================
// CopyIn - Transfer data from GM to UB
// ============================================================================
template <typename T>
__aicore__ inline void Sinh<T>::CopyIn(int64_t progress, int64_t currentNum)
{
    AscendC::LocalTensor<T> xLocal = inputQueue.AllocTensor<T>();
    AscendC::DataCopyParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = currentNum * sizeof(T);
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;
    AscendC::DataCopyPad(xLocal, inputGM[progress * ubLength_], copyParams, {false, 0, 0, 0});
    inputQueue.EnQue(xLocal);
}

// ============================================================================
// CopyOut - Transfer data from UB to GM
// ============================================================================
template <typename T>
__aicore__ inline void Sinh<T>::CopyOut(int64_t progress, int64_t currentNum)
{
    AscendC::LocalTensor<T> yLocal = outputQueue.DeQue<T>();
    AscendC::DataCopyParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = currentNum * sizeof(T);
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;
    AscendC::DataCopyPad(outputGM[progress * ubLength_], yLocal, copyParams);
    outputQueue.FreeTensor(yLocal);
}

// ============================================================================
// Compute - float32 specialization
// ============================================================================
template <>
__aicore__ inline void Sinh<float>::Compute(int64_t currentNum)
{
    AscendC::LocalTensor<float> xLocal = inputQueue.DeQue<float>();
    AscendC::LocalTensor<float> yLocal = outputQueue.AllocTensor<float>();
    AscendC::LocalTensor<float> expPos = tmpBuf1.Get<float>();
    AscendC::LocalTensor<float> expNeg = tmpBuf2.Get<float>();

    AscendC::Exp(expPos, xLocal, currentNum);
    AscendC::Muls(xLocal, xLocal, static_cast<float>(-1.0f), currentNum);
    AscendC::Exp(expNeg, xLocal, currentNum);
    AscendC::Sub(expPos, expPos, expNeg, currentNum);
    AscendC::Muls(yLocal, expPos, static_cast<float>(0.5f), currentNum);

    outputQueue.EnQue<float>(yLocal);
    inputQueue.FreeTensor(xLocal);
}

// ============================================================================
// Compute - float16 specialization: cast to float32, compute, cast back
// ============================================================================
template <>
__aicore__ inline void Sinh<half>::Compute(int64_t currentNum)
{
    AscendC::LocalTensor<half> xLocal = inputQueue.DeQue<half>();
    AscendC::LocalTensor<half> yLocal = outputQueue.AllocTensor<half>();
    AscendC::LocalTensor<float> xFloat = tmpBuf1.Get<float>();
    AscendC::LocalTensor<float> expNeg = tmpBuf2.Get<float>();

    AscendC::Cast(xFloat, xLocal, AscendC::RoundMode::CAST_NONE, currentNum);
    AscendC::Exp(expNeg, xFloat, currentNum);
    AscendC::Muls(xFloat, xFloat, static_cast<float>(-1.0f), currentNum);
    AscendC::Exp(xFloat, xFloat, currentNum);
    AscendC::Sub(expNeg, expNeg, xFloat, currentNum);
    AscendC::Muls(xFloat, expNeg, static_cast<float>(0.5f), currentNum);
    AscendC::Cast(yLocal, xFloat, AscendC::RoundMode::CAST_ROUND, currentNum);

    outputQueue.EnQue<half>(yLocal);
    inputQueue.FreeTensor(xLocal);
}

// ============================================================================
// Compute - bfloat16 specialization: cast to float32, compute, cast back
// ============================================================================
template <>
__aicore__ inline void Sinh<bfloat16_t>::Compute(int64_t currentNum)
{
    AscendC::LocalTensor<bfloat16_t> xLocal = inputQueue.DeQue<bfloat16_t>();
    AscendC::LocalTensor<bfloat16_t> yLocal = outputQueue.AllocTensor<bfloat16_t>();
    AscendC::LocalTensor<float> xFloat = tmpBuf1.Get<float>();
    AscendC::LocalTensor<float> expNeg = tmpBuf2.Get<float>();

    AscendC::Cast(xFloat, xLocal, AscendC::RoundMode::CAST_NONE, currentNum);
    AscendC::Exp(expNeg, xFloat, currentNum);
    AscendC::Muls(xFloat, xFloat, static_cast<float>(-1.0f), currentNum);
    AscendC::Exp(xFloat, xFloat, currentNum);
    AscendC::Sub(expNeg, expNeg, xFloat, currentNum);
    AscendC::Muls(xFloat, expNeg, static_cast<float>(0.5f), currentNum);
    AscendC::Cast(yLocal, xFloat, AscendC::RoundMode::CAST_ROUND, currentNum);

    outputQueue.EnQue<bfloat16_t>(yLocal);
    inputQueue.FreeTensor(xLocal);
}

// ============================================================================
// Process - Main loop
// ============================================================================
template <typename T>
__aicore__ inline void Sinh<T>::Process()
{
    if (blockLength_ <= 0 || ubLength_ <= 0) {
        return;
    }
    int64_t loopCount = (blockLength_ + ubLength_ - 1) / ubLength_;
    for (int64_t i = 0; i < loopCount; i++) {
        int64_t currentNum = (i == (loopCount - 1)) ? (blockLength_ - ubLength_ * i) : ubLength_;
        CopyIn(i, currentNum);
        Compute(currentNum);
        CopyOut(i, currentNum);
    }
}

} // namespace NsSinh
#endif // SINH_H
