/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sinh_apt.cpp
 * \brief z = sinh(x) for ascend950 (arch35)
 */
#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "arch35/sinh.h"

enum class SinhTilingKey : uint32_t
{
    TILING_KEY_FLOAT32 = 0,
    TILING_KEY_FLOAT16 = 1,
    TILING_KEY_BFLOAT16 = 2,
};

template <uint32_t schMode>
__global__ __aicore__ void sinh(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(SinhTilingData);
    GET_TILING_DATA_WITH_STRUCT(SinhTilingData, tilingData, tiling);
    if constexpr (schMode == static_cast<uint32_t>(SinhTilingKey::TILING_KEY_FLOAT32)) {
        NsSinh::Sinh<float> op;
        op.Init(x, y, &tilingData);
        op.Process();
    }
    if constexpr (schMode == static_cast<uint32_t>(SinhTilingKey::TILING_KEY_FLOAT16)) {
        NsSinh::Sinh<half> op;
        op.Init(x, y, &tilingData);
        op.Process();
    }
    if constexpr (schMode == static_cast<uint32_t>(SinhTilingKey::TILING_KEY_BFLOAT16)) {
        NsSinh::Sinh<bfloat16_t> op;
        op.Init(x, y, &tilingData);
        op.Process();
    }
}
